spring:
  application:
    name: delivery-service

server:
  port: 9192



logging:
  file:
    name: delivery-service/logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    web: error
    root: info
    sql: error
    org.springframework.security: trace
com:
  amazonaws:
    xray:
      serviceName: Delivery-Service
      sampling:
        enabled: true
        rules: classpath:/sampling-rules.json
  logging:
    level:
      com:
        amazonaws:
          xray: DEBUG